kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: default-receiver
    receivers:
      - name: default-receiver
        emailConfigs:
          - to: 
            from: 
            smarthost: smtp.gmail.com:587
            authUsername:
            authPassword: 
            requireTLS: true