services:
  model:
    image: "ghcr.io/remla23-team09/model-service"
    ports:
     - "8081:8080"
  web:
    image: "ghcr.io/remla23-team09/app"
    ports:
     - "8080:8080"
    environment:
     - MODEL_HOST=http://model:8080