services:
  model:
    image: "ghcr.io/remla23-team09/model-service:0.0.7"
    ports:
     - "8081:8080"
  web:
    image: "ghcr.io/remla23-team09/app:0.0.6"
    ports:
     - "8080:8080"
    environment:
     - MODEL_HOST=http://model:8080