apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels: {app: app, version: v1}
spec:
  replicas: 1
  selector:
    matchLabels: {app: app, version: v1}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels: {app: app, version: v1}
    spec:
      containers:
      - name: app
        image: ghcr.io/remla23-team09/app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:  
                name: app-config
                key: MODEL_HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels: {app: app, version: v2}
spec:
  replicas: 1
  selector:
    matchLabels: {app: app, version: v2}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels: {app: app, version: v2}
    spec:
      containers:
      - name: app
        image: ghcr.io/remla23-team09/app:0.0.19
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:  
                name: app-config
                key: MODEL_HOST