{
 "title": "remla23-team09",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Comparison application versions, number of predictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$happy_v1 + $sad_v1\n", "type": "math" },
    { "expression": "$happy_v2 + $sad_v2\n", "type": "math" }
   ]
  },
  {
   "title": "Predictions Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(counter_sad_predictions_total)",
     "legendFormat": "Sad Predictions"
    },
    {
     "expr": "sum(counter_happy_predictions_total)",
     "legendFormat": "Happy Predictions"
    },
    {
     "expression": "$sad_predictions + $happy_predictions",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total Model Prediction Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "summary_time_sum{step=\"prediction\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Model Prediction Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(gauge_time{step=\"prediction\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of data input (number of characters) current version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_size_of_input_bucket{version=\"v1\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Processing Model Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "summary_time_sum{step=\"processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Model Processing Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gauge_time{step=\"processing\"}",
     "legendFormat": "s"
    }
   ]
  },
  {
   "title": "Size of data input (number of characters) new version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_size_of_input_bucket{version=\"v2\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}