{
 "title": "remla23-team09",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Model Prediction Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "summary_time_sum{step=\"prediction\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Model Prediction Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(gauge_time{step=\"prediction\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "counter_sad_predictions_total", "legendFormat": "Sad Predictions" },
    {
     "expr": "counter_happy_predictions_total",
     "legendFormat": "Happy Predictions"
    },
    {
     "expression": "$sad_predictions + $happy_predictions",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total Processing Model Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "summary_time_sum{step=\"processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Model Processing Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gauge_time{step=\"processing\"}",
     "legendFormat": "s"
    }
   ]
  },
  {
   "title": "Size of data input (number of characters)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "histogram_size_of_input_bucket", "legendFormat": "__auto" }
   ]
  }
 ]
}