apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
    service: model-service
spec:
  selector:
    app: model-service
  ports:
  - port: 8080
    name: tcp-modelservice