service:
  type: LoadBalancer
  loadBalancerIP: "34.32.188.221"
  nodePorts:
    grafana: 80

ingress:
  enabled: true
  hostname: "grafana.remla23-team09.com"

dashboardsProvider:
  enabled: true

dashboardsConfigMaps[0]:
  configMapName: "remla23-team09"
  fileName: "remla23-team09.json"