grafana-operator:
  grafana:
    config:
      server:
        root_url: "https://grafana.remla23-team09.com"

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL

dashboardProviders:
  enabled: true
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps[0]:
    configMapName: "remla23-team09"
    fileName: "remla23-team09.json"