admin:
  existingSecret: "grafana-admin-credentials"
  userKey: "username"
  passwordKey: "password"

service:
  type: ClusterIP
  clusterIP: "34.32.188.221"
  ports:
    grafana: 80

dashboardsProvider:
  enabled: true
  configMapName: ""

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090  
      access: proxy
      isDefault: true

dashboardsConfigMaps:
  - configMapName: "remla23-team09"
    fileName: "remla23-team09.json"