service:
  type: LoadBalancer
  loadBalancerIP: "34.32.188.221"
  ports:
    grafana: 80

dashboardsProvider:
  enabled: true


dashboardsConfigMaps[0]:
  configMapName: "remla23-team09"
  fileName: "remla23-team09.json"