name: Plan & Apply Terraform Kubernetes Codebase
run-name: (TF-K8S) ${{ github.run_number }}
on:
  workflow_dispatch:
jobs:
  plan:
    name: 1 - Terraform Plan
    runs-on: ubuntu-22.04
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA }}
      - id: gke
        name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: remla23-team09-gke
          location: europe-west4
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/kubernetes
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform/kubernetes
  apply:
    name: 2 - Terraform Apply
    needs: plan
    runs-on: ubuntu-22.04
    environment: terraform-apply
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/kubernetes
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
      - name: Terraform Apply
        run: terraform apply --auto-approve -no-color
        working-directory: ./terraform/kubernetes
