name: Plan & Apply Terraform Kubernetes Codebase
run-name: "TF-K8S: ${{ github.event.head_commit.message }}"
on:
  workflow_dispatch:
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-22.04
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/kubernetes
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform/kubernetes
  apply:
    name: Terraform Plan
    runs-on: ubuntu-22.04
    environment: terraform-apply
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/kubernetes
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
      - name: Terraform Apply
        run: terraform apply --auto-approve -no-color
        working-directory: ./terraform/kubernetes